# Generated by Django 3.0.8 on 2020-12-23 14:43

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chanpionship', models.CharField(max_length=200, verbose_name='Campionato')),
                ('place', models.CharField(max_length=200, verbose_name='Luogo')),
                ('date', models.DateField(blank=True, default=django.utils.timezone.now, verbose_name='Data')),
                ('time', models.TimeField(blank=True, default=django.utils.timezone.now, verbose_name='Hora')),
                ('weather', models.CharField(max_length=200, verbose_name='Tempo')),
                ('temperature', models.CharField(max_length=200, verbose_name='Temperatura')),
                ('team_a', models.CharField(max_length=200, verbose_name='Squadra di Casa')),
                ('team_b', models.CharField(max_length=200, verbose_name='Squadra Ospite')),
            ],
            options={
                'verbose_name_plural': 'Partite',
            },
        ),
        migrations.CreateModel(
            name='Stats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_half', models.TimeField(blank=True, max_length=200, verbose_name='Primo Tempo')),
                ('second_half', models.TimeField(blank=True, max_length=200, verbose_name='Secondo Tempo')),
                ('possession1A', models.TimeField(blank=True, max_length=200, verbose_name='Possesso Palla Squadra A Primo Tempo')),
                ('possession1B', models.TimeField(blank=True, max_length=200, verbose_name='Possesso Palla Squadra B Primo Tempo')),
                ('possession2A', models.TimeField(blank=True, max_length=200, verbose_name='Possesso Palla Squadra A Secondo Tempo')),
                ('possession2B', models.TimeField(blank=True, max_length=200, verbose_name='Possesso Palla Squadra B Secondo Tempo')),
                ('tiri_in_porta1_sx', models.IntegerField(blank=True, null=True, verbose_name='Tiri in porta a sinistra Primo Tempo')),
                ('tiri_in_porta1_dx', models.IntegerField(blank=True, null=True, verbose_name='Tiri in porta a destra Primo Tempo')),
                ('tiri_in_porta1_cc', models.IntegerField(blank=True, null=True, verbose_name='Tiri in porta al centro Primo Tempo')),
                ('tiri_in_fuori1_sx', models.IntegerField(blank=True, null=True, verbose_name='Tiri in fuori a sinistra Primo Tempo')),
                ('tiri_in_fuori1_dx', models.IntegerField(blank=True, null=True, verbose_name='Tiri in fuori a destra Primo Tempo')),
                ('tiri_in_fuori1_cc', models.IntegerField(blank=True, null=True, verbose_name='Tiri in fuori al centro Primo Tempo')),
                ('punizioni_difensive1_sx', models.IntegerField(blank=True, null=True, verbose_name='Punizioni difensive a sinistra Primo Tempo')),
                ('punizioni_difensive1_dx', models.IntegerField(blank=True, null=True, verbose_name='Punizioni difensive a destra Primo Tempo')),
                ('punizioni_difensive1_cc', models.IntegerField(blank=True, null=True, verbose_name='Punizioni difensive al centro Primo Tempo')),
                ('punizioni_offensive1_dx', models.IntegerField(blank=True, null=True, verbose_name='Punzioni offensive a destra Primo Tempo')),
                ('punizioni_offensive1_cc', models.IntegerField(blank=True, null=True, verbose_name='Punzioni offensive al centro Primo Tempo')),
                ('punizioni_offensive1_sx', models.IntegerField(blank=True, null=True, verbose_name='Punzioni offensive a sinistra Primo Tempo')),
                ('cross_dx1', models.IntegerField(blank=True, null=True, verbose_name='Cross a destra Primo Tempo')),
                ('cross_cc1', models.IntegerField(blank=True, null=True, verbose_name='Cross al centro Primo Tempo')),
                ('cross_sx1', models.IntegerField(blank=True, null=True, verbose_name='Cross a sinistra Primo Tempo')),
                ('corners1', models.IntegerField(blank=True, null=True, verbose_name="Calci d'angolo Primo Tempo")),
                ('parate1', models.IntegerField(blank=True, null=True, verbose_name='Parate Primo Tempo')),
                ('fuorigioco1', models.IntegerField(blank=True, null=True, verbose_name='Fuorigioco Primo Tempo')),
                ('tiri_in_porta2_sx', models.IntegerField(blank=True, null=True, verbose_name='Tiri in porta a sinistra Secondo Tempo')),
                ('tiri_in_porta2_dx', models.IntegerField(blank=True, null=True, verbose_name='Tiri in porta a destra Secondo Tempo')),
                ('tiri_in_porta2_cc', models.IntegerField(blank=True, null=True, verbose_name='Tiri in porta al centro SecondoTempo')),
                ('tiri_in_fuori2_sx', models.IntegerField(blank=True, null=True, verbose_name='Tiri in fuori a sinistra Secondo Tempo')),
                ('tiri_in_fuori2_dx', models.IntegerField(blank=True, null=True, verbose_name='Tiri in fuori a destra Secondo Tempo')),
                ('tiri_in_fuori2_cc', models.IntegerField(blank=True, null=True, verbose_name='Tiri in fuori al centro SecondoTempo')),
                ('punizioni_difensive2_sx', models.IntegerField(blank=True, null=True, verbose_name='Punizioni difensive a sinistra Secondo Tempo')),
                ('punizioni_difensive2_dx', models.IntegerField(blank=True, null=True, verbose_name='Punizioni difensive a destra Secondo Tempo')),
                ('punizioni_difensive2_cc', models.IntegerField(blank=True, null=True, verbose_name='Punizioni difensive al centro SecondoTempo')),
                ('punizioni_offensive2_dx', models.IntegerField(blank=True, null=True, verbose_name='Punzioni offensive a destra Secondo Tempo')),
                ('punizioni_offensive2_cc', models.IntegerField(blank=True, null=True, verbose_name='Punzioni offensive al centro SecondoTempo')),
                ('punizioni_offensive2_sx', models.IntegerField(blank=True, null=True, verbose_name='Punzioni offensive a sinistra Secondo Tempo')),
                ('cross_dx2', models.IntegerField(blank=True, null=True, verbose_name='Cross a destra Secondo Tempo')),
                ('cross_cc2', models.IntegerField(blank=True, null=True, verbose_name='Cross al centro SecondoTempo')),
                ('cross_sx2', models.IntegerField(blank=True, null=True, verbose_name='Cross a sinistra Secondo Tempo')),
                ('corners2', models.IntegerField(blank=True, null=True, verbose_name="Calci d'angolo Secondo Tempo")),
                ('parate2', models.IntegerField(blank=True, null=True, verbose_name='Parate Secondo Tempo')),
                ('fuorigioco2', models.IntegerField(blank=True, null=True, verbose_name='Fuorigioco Secondo Tempo')),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stats', to='core.Match')),
            ],
            options={
                'verbose_name_plural': 'Statistiche',
            },
        ),
    ]
