# Generated by Django 3.0.8 on 2020-12-23 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20201223_1650'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stats',
            name='corners2',
        ),
        migrations.RemoveField(
            model_name='stats',
            name='cross_cc2',
        ),
        migrations.RemoveField(
            model_name='stats',
            name='cross_dx2',
        ),
        migrations.RemoveField(
            model_name='stats',
            name='cross_sx2',
        ),
        migrations.RemoveField(
            model_name='stats',
            name='fuorigioco2',
        ),
        migrations.RemoveField(
            model_name='stats',
            name='parate2',
        ),
        migrations.RemoveField(
            model_name='stats',
            name='punizioni_difensive2_cc',
        ),
        migrations.RemoveField(
            model_name='stats',
            name='punizioni_difensive2_dx',
        ),
        migrations.RemoveField(
            model_name='stats',
            name='punizioni_difensive2_sx',
        ),
        migrations.RemoveField(
            model_name='stats',
            name='punizioni_offensive2_cc',
        ),
        migrations.RemoveField(
            model_name='stats',
            name='punizioni_offensive2_dx',
        ),
        migrations.RemoveField(
            model_name='stats',
            name='punizioni_offensive2_sx',
        ),
        migrations.RemoveField(
            model_name='stats',
            name='tiri_in_fuori2_cc',
        ),
        migrations.RemoveField(
            model_name='stats',
            name='tiri_in_fuori2_dx',
        ),
        migrations.RemoveField(
            model_name='stats',
            name='tiri_in_fuori2_sx',
        ),
        migrations.RemoveField(
            model_name='stats',
            name='tiri_in_porta2_cc',
        ),
        migrations.RemoveField(
            model_name='stats',
            name='tiri_in_porta2_dx',
        ),
        migrations.RemoveField(
            model_name='stats',
            name='tiri_in_porta2_sx',
        ),
        migrations.AddField(
            model_name='stats',
            name='corners1B',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name="Calci d'angolo Primo Tempo Squadra B"),
        ),
        migrations.AddField(
            model_name='stats',
            name='corners2A',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name="Calci d'angolo Secondo Tempo Squadra A"),
        ),
        migrations.AddField(
            model_name='stats',
            name='corners2B',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name="Calci d'angolo Secondo Tempo Squadra B"),
        ),
        migrations.AddField(
            model_name='stats',
            name='cross_cc1B',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Cross al centro Primo Tempo Squadra B'),
        ),
        migrations.AddField(
            model_name='stats',
            name='cross_cc2A',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Cross al centro SecondoTempo Squadra A'),
        ),
        migrations.AddField(
            model_name='stats',
            name='cross_cc2B',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Cross al centro SecondoTempo Squadra B'),
        ),
        migrations.AddField(
            model_name='stats',
            name='cross_dx1B',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Cross a destra Primo Tempo Squadra B'),
        ),
        migrations.AddField(
            model_name='stats',
            name='cross_dx2A',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Cross a destra Secondo Tempo Squadra A'),
        ),
        migrations.AddField(
            model_name='stats',
            name='cross_dx2B',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Cross a destra Secondo Tempo Squadra B'),
        ),
        migrations.AddField(
            model_name='stats',
            name='cross_sx1B',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Cross a sinistra Primo Tempo Squadra B'),
        ),
        migrations.AddField(
            model_name='stats',
            name='cross_sx2A',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Cross a sinistra Secondo Tempo Squadra A'),
        ),
        migrations.AddField(
            model_name='stats',
            name='cross_sx2B',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Cross a sinistra Secondo Tempo Squadra B'),
        ),
        migrations.AddField(
            model_name='stats',
            name='fuorigioco1B',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Fuorigioco Primo Tempo Squadra B'),
        ),
        migrations.AddField(
            model_name='stats',
            name='fuorigioco2A',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Fuorigioco Secondo Tempo Squadra A'),
        ),
        migrations.AddField(
            model_name='stats',
            name='fuorigioco2B',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Fuorigioco Secondo Tempo Squadra B'),
        ),
        migrations.AddField(
            model_name='stats',
            name='parate1B',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Parate Primo Tempo Squadra B'),
        ),
        migrations.AddField(
            model_name='stats',
            name='parate2A',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Parate Secondo Tempo Squadra A'),
        ),
        migrations.AddField(
            model_name='stats',
            name='parate2B',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Parate Secondo Tempo Squadra B'),
        ),
        migrations.AddField(
            model_name='stats',
            name='punizioni_difensive1B_cc',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Punizioni difensive al centro Primo Tempo Squadra B'),
        ),
        migrations.AddField(
            model_name='stats',
            name='punizioni_difensive1B_dx',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Punizioni difensive a destra Primo Tempo Squadra B'),
        ),
        migrations.AddField(
            model_name='stats',
            name='punizioni_difensive1B_sx',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Punizioni difensive a sinistra Primo Tempo Squadra B'),
        ),
        migrations.AddField(
            model_name='stats',
            name='punizioni_difensive2A_cc',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Punizioni difensive al centro SecondoTempo Squadra A'),
        ),
        migrations.AddField(
            model_name='stats',
            name='punizioni_difensive2A_dx',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Punizioni difensive a destra Secondo Tempo Squadra A'),
        ),
        migrations.AddField(
            model_name='stats',
            name='punizioni_difensive2A_sx',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Punizioni difensive a sinistra Secondo Tempo Squadra A'),
        ),
        migrations.AddField(
            model_name='stats',
            name='punizioni_difensive2B_cc',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Punizioni difensive al centro SecondoTempo Squadra B'),
        ),
        migrations.AddField(
            model_name='stats',
            name='punizioni_difensive2B_dx',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Punizioni difensive a destra Secondo Tempo Squadra B'),
        ),
        migrations.AddField(
            model_name='stats',
            name='punizioni_difensive2B_sx',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Punizioni difensive a sinistra Secondo Tempo Squadra B'),
        ),
        migrations.AddField(
            model_name='stats',
            name='punizioni_offensive1B_cc',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Punzioni offensive al centro Primo Tempo Squadra B'),
        ),
        migrations.AddField(
            model_name='stats',
            name='punizioni_offensive1B_dx',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Punzioni offensive a destra Primo Tempo Squadra B'),
        ),
        migrations.AddField(
            model_name='stats',
            name='punizioni_offensive1B_sx',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Punzioni offensive a sinistra Primo Tempo Squadra B'),
        ),
        migrations.AddField(
            model_name='stats',
            name='punizioni_offensive2A_cc',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Punzioni offensive al centro SecondoTempo Squadra A'),
        ),
        migrations.AddField(
            model_name='stats',
            name='punizioni_offensive2A_dx',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Punzioni offensive a destra Secondo Tempo Squadra A'),
        ),
        migrations.AddField(
            model_name='stats',
            name='punizioni_offensive2A_sx',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Punzioni offensive a sinistra Secondo Tempo Squadra A'),
        ),
        migrations.AddField(
            model_name='stats',
            name='punizioni_offensive2B_cc',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Punzioni offensive al centro SecondoTempo Squadra B'),
        ),
        migrations.AddField(
            model_name='stats',
            name='punizioni_offensive2B_dx',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Punzioni offensive a destra Secondo Tempo Squadra B'),
        ),
        migrations.AddField(
            model_name='stats',
            name='punizioni_offensive2B_sx',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Punzioni offensive a sinistra Secondo Tempo Squadra B'),
        ),
        migrations.AddField(
            model_name='stats',
            name='tiri_in_fuori1B_cc',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Tiri in fuori al centro Primo Tempo Squadra B'),
        ),
        migrations.AddField(
            model_name='stats',
            name='tiri_in_fuori1B_dx',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Tiri in fuori a destra Primo Tempo Squadra B'),
        ),
        migrations.AddField(
            model_name='stats',
            name='tiri_in_fuori1B_sx',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Tiri in fuori a sinistra Primo Tempo Squadra B'),
        ),
        migrations.AddField(
            model_name='stats',
            name='tiri_in_fuori2A_cc',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Tiri in fuori al centro SecondoTempo Squadra A'),
        ),
        migrations.AddField(
            model_name='stats',
            name='tiri_in_fuori2A_dx',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Tiri in fuori a destra Secondo Tempo Squadra A'),
        ),
        migrations.AddField(
            model_name='stats',
            name='tiri_in_fuori2A_sx',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Tiri in fuori a sinistra Secondo Tempo Squadra A'),
        ),
        migrations.AddField(
            model_name='stats',
            name='tiri_in_fuori2B_cc',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Tiri in fuori al centro SecondoTempo Squadra B'),
        ),
        migrations.AddField(
            model_name='stats',
            name='tiri_in_fuori2B_dx',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Tiri in fuori a destra Secondo Tempo Squadra B'),
        ),
        migrations.AddField(
            model_name='stats',
            name='tiri_in_fuori2B_sx',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Tiri in fuori a sinistra Secondo Tempo Squadra B'),
        ),
        migrations.AddField(
            model_name='stats',
            name='tiri_in_porta1B_cc',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Tiri in porta al centro Primo Tempo Squadra B'),
        ),
        migrations.AddField(
            model_name='stats',
            name='tiri_in_porta1B_dx',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Tiri in porta a destra Primo Tempo Squadra B'),
        ),
        migrations.AddField(
            model_name='stats',
            name='tiri_in_porta1B_sx',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Tiri in porta a sinistra Primo Tempo Squadra B'),
        ),
        migrations.AddField(
            model_name='stats',
            name='tiri_in_porta2A_cc',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Tiri in porta al centro SecondoTempo Squadra A'),
        ),
        migrations.AddField(
            model_name='stats',
            name='tiri_in_porta2A_dx',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Tiri in porta a destra Secondo Tempo Squadra A'),
        ),
        migrations.AddField(
            model_name='stats',
            name='tiri_in_porta2A_sx',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Tiri in porta a sinistra Secondo Tempo Squadra A'),
        ),
        migrations.AddField(
            model_name='stats',
            name='tiri_in_porta2B_cc',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Tiri in porta al centro SecondoTempo Squadra B'),
        ),
        migrations.AddField(
            model_name='stats',
            name='tiri_in_porta2B_dx',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Tiri in porta a destra Secondo Tempo Squadra B'),
        ),
        migrations.AddField(
            model_name='stats',
            name='tiri_in_porta2B_sx',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Tiri in porta a sinistra Secondo Tempo Squadra B'),
        ),
    ]
