# Generated by Django 3.0.8 on 2020-12-29 16:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20201223_1705'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.CharField(blank=True, max_length=200, null=True, verbose_name='Nuovo evento')),
                ('eventtime', models.TimeField(blank=True, null=True, verbose_name='Minuto del nuovo evento')),
                ('team', models.CharField(max_length=200, verbose_name='Squadra')),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event', to='core.Match')),
            ],
        ),
    ]
