# Generated by Django 3.0.8 on 2020-12-30 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_event'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stats',
            name='first_half',
            field=models.TimeField(blank=True, default='00:00:00', max_length=200, null=True, verbose_name='Primo Tempo'),
        ),
        migrations.AlterField(
            model_name='stats',
            name='second_half',
            field=models.TimeField(blank=True, default='00:00:00', max_length=200, null=True, verbose_name='Secondo Tempo'),
        ),
    ]
