# Generated by Django 3.0.8 on 2021-01-05 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20210105_1837'),
    ]

    operations = [
        migrations.AddField(
            model_name='stats',
            name='cross1B',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Cross  Primo Tempo Squadra B'),
        ),
        migrations.AddField(
            model_name='stats',
            name='cross2A',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Cross  Secondo Tempo Squadra A'),
        ),
        migrations.AddField(
            model_name='stats',
            name='cross2B',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Cross  Secondo Tempo Squadra B'),
        ),
        migrations.AddField(
            model_name='stats',
            name='punizioni_difensive1B',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Punizioni difensive  Primo Tempo Squadra B'),
        ),
        migrations.AddField(
            model_name='stats',
            name='punizioni_difensive2A',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Punizioni difensive  Secondo Tempo Squadra A'),
        ),
        migrations.AddField(
            model_name='stats',
            name='punizioni_difensive2B',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Punizioni difensive  Secondo Tempo Squadra B'),
        ),
        migrations.AddField(
            model_name='stats',
            name='punizioni_offensive1B',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Punzioni offensive Primo Tempo Squadra B'),
        ),
        migrations.AddField(
            model_name='stats',
            name='punizioni_offensive2A',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Punzioni offensive Secondo Tempo Squadra A'),
        ),
        migrations.AddField(
            model_name='stats',
            name='punizioni_offensive2B',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Punzioni offensive Secondo Tempo Squadra B'),
        ),
        migrations.AddField(
            model_name='stats',
            name='tiri_in_fuori1B',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Tiri in fuori Primo Tempo Squadra B'),
        ),
        migrations.AddField(
            model_name='stats',
            name='tiri_in_fuori2A',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Tiri in fuori Secondo Tempo Squadra A'),
        ),
        migrations.AddField(
            model_name='stats',
            name='tiri_in_fuori2B',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Tiri in fuori Secondo Tempo Squadra B'),
        ),
        migrations.AddField(
            model_name='stats',
            name='tiri_in_porta1B',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Tiri in porta Primo Tempo Squadra B'),
        ),
        migrations.AddField(
            model_name='stats',
            name='tiri_in_porta2A',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Tiri in porta Secondo Tempo Squadra A'),
        ),
        migrations.AddField(
            model_name='stats',
            name='tiri_in_porta2B',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Tiri in porta Secondo Tempo Squadra B'),
        ),
    ]
