# Generated by Django 3.0.8 on 2021-01-07 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20210105_1850'),
    ]

    operations = [
        migrations.AddField(
            model_name='stats',
            name='corners',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Total corners '),
        ),
        migrations.AddField(
            model_name='stats',
            name='corners1',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Totale corners Primo Tempo'),
        ),
        migrations.AddField(
            model_name='stats',
            name='corners2',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Totale corners Secondo Tempo'),
        ),
        migrations.AddField(
            model_name='stats',
            name='cross',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Total cross '),
        ),
        migrations.AddField(
            model_name='stats',
            name='cross1',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Totale cross Primo Tempo'),
        ),
        migrations.AddField(
            model_name='stats',
            name='cross2',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Totale cross Secondo Tempo'),
        ),
        migrations.AddField(
            model_name='stats',
            name='fuorigioco',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Total fuorigioco '),
        ),
        migrations.AddField(
            model_name='stats',
            name='fuorigioco1',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Totale fuorigioco Primo Tempo'),
        ),
        migrations.AddField(
            model_name='stats',
            name='fuorigioco2',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Totale fuorigioco Secondo Tempo'),
        ),
        migrations.AddField(
            model_name='stats',
            name='parate',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Total parate '),
        ),
        migrations.AddField(
            model_name='stats',
            name='parate1',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Totale parate Primo Tempo'),
        ),
        migrations.AddField(
            model_name='stats',
            name='parate2',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Totale parate Secondo Tempo'),
        ),
        migrations.AddField(
            model_name='stats',
            name='punizioni_difensive',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Total Punizioni difensive '),
        ),
        migrations.AddField(
            model_name='stats',
            name='punizioni_difensive1',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Totale Punizioni difensive Primo Tempo'),
        ),
        migrations.AddField(
            model_name='stats',
            name='punizioni_difensive2',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Totale Punizioni difensive Secondo Tempo'),
        ),
        migrations.AddField(
            model_name='stats',
            name='punizioni_offensive',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Total Punizioni Offensive '),
        ),
        migrations.AddField(
            model_name='stats',
            name='punizioni_offensive1',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Totale Punizioni Offensive Primo Tempo'),
        ),
        migrations.AddField(
            model_name='stats',
            name='punizioni_offensive2',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Totale Punizioni Offensive Secondo Tempo'),
        ),
        migrations.AddField(
            model_name='stats',
            name='tiri_in_fuori',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Total Tiri in fuori '),
        ),
        migrations.AddField(
            model_name='stats',
            name='tiri_in_fuori1',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Totale Tiri in fuori Primo Tempo'),
        ),
        migrations.AddField(
            model_name='stats',
            name='tiri_in_fuori2',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Totale Tiri in fuori Secondo Tempo'),
        ),
        migrations.AddField(
            model_name='stats',
            name='tiri_in_porta',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Total Tiri in porta '),
        ),
        migrations.AddField(
            model_name='stats',
            name='tiri_in_porta1',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Totale Tiri in porta Primo Tempo'),
        ),
        migrations.AddField(
            model_name='stats',
            name='tiri_in_porta2',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Totale Tiri in porta Secondo Tempo'),
        ),
    ]
