# Generated by Django 3.0.8 on 2021-01-14 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20210114_1445'),
    ]

    operations = [
        migrations.AddField(
            model_name='stats',
            name='possessionA',
            field=models.TimeField(blank=True, default='00:00:00', max_length=200, null=True, verbose_name='Possesso Palla Squadra A '),
        ),
        migrations.AddField(
            model_name='stats',
            name='possessionB',
            field=models.TimeField(blank=True, default='00:00:00', max_length=200, null=True, verbose_name='Possesso Palla Squadra B'),
        ),
    ]
