from django.db import models
from django.utils import timezone

# Create your models here.
class Match(models.Model):
    chanpionship = models.CharField(max_length=200, verbose_name = 'Campionato')
    place = models.CharField(max_length=200, verbose_name = 'Luogo')
    date = models.DateField(default=timezone.now, blank=True, verbose_name="Data")
    time = models.TimeField(default=timezone.now, blank=True, verbose_name = 'Hora')
    weather = models.CharField(max_length=200, verbose_name = 'Tempo')
    temperature = models.CharField(max_length=200, verbose_name = 'Temperatura')
    team_a = models.CharField(max_length=200, verbose_name = 'Squadra di Casa')
    team_b = models.CharField(max_length=200, verbose_name = 'Squadra Ospite')

    def __str__(self):
        return (self.team_a + " vs " + self.team_b + " in data " + str(self.date))

    class Meta:
        verbose_name_plural = "Partite"

class Stats(models.Model):
    match = models.ForeignKey(Match, on_delete=models.CASCADE, related_name='stats')
    first_half = models.TimeField(max_length=200, blank=True, null=True, verbose_name = 'Primo Tempo')
    second_half = models.TimeField(max_length=200, blank=True, null=True, verbose_name = 'Secondo Tempo')
    possession1A= models.TimeField(max_length=200, blank=True, null=True, verbose_name = 'Possesso Palla Squadra A Primo Tempo')
    possession1B = models.TimeField(max_length=200, blank=True, null=True, verbose_name = 'Possesso Palla Squadra B Primo Tempo')
    possession2A= models.TimeField(max_length=200, blank=True, null=True, verbose_name = 'Possesso Palla Squadra A Secondo Tempo')
    possession2B = models.TimeField(max_length=200, blank=True, null=True, verbose_name = 'Possesso Palla Squadra B Secondo Tempo')
    tiri_in_porta1A_sx = models.IntegerField(null=True, blank=True, default=0, verbose_name = "Tiri in porta a sinistra Primo Tempo Squadra A")
    tiri_in_porta1A_dx = models.IntegerField(null=True, blank=True, default=0, verbose_name = "Tiri in porta a destra Primo Tempo Squadra A")
    tiri_in_porta1A_cc = models.IntegerField(null=True, blank=True, default=0, verbose_name = "Tiri in porta al centro Primo Tempo Squadra A")
    tiri_in_fuori1A_sx = models.IntegerField(null=True, blank=True, default=0, verbose_name = "Tiri in fuori a sinistra Primo Tempo Squadra A")
    tiri_in_fuori1A_dx = models.IntegerField(null=True, blank=True, default=0, verbose_name = "Tiri in fuori a destra Primo Tempo Squadra A")
    tiri_in_fuori1A_cc = models.IntegerField(null=True, blank=True, default=0, verbose_name = "Tiri in fuori al centro Primo Tempo Squadra A")
    punizioni_difensive1A_sx = models.IntegerField(null=True, blank=True, default=0, verbose_name = "Punizioni difensive a sinistra Primo Tempo Squadra A")
    punizioni_difensive1A_dx = models.IntegerField(null=True, blank=True, default=0, verbose_name = "Punizioni difensive a destra Primo Tempo Squadra A")
    punizioni_difensive1A_cc = models.IntegerField(null=True, blank=True, default=0, verbose_name = "Punizioni difensive al centro Primo Tempo Squadra A")
    punizioni_offensive1A_sx = models.IntegerField(null=True, blank=True, default=0, verbose_name = "Punzioni offensive a sinistra Primo Tempo Squadra A")
    punizioni_offensive1A_dx = models.IntegerField(null=True, blank=True, default=0, verbose_name = "Punzioni offensive a destra Primo Tempo Squadra A")
    punizioni_offensive1A_cc = models.IntegerField(null=True, blank=True, default=0, verbose_name = "Punzioni offensive al centro Primo Tempo Squadra A")
    punizioni_offensive1A_sx = models.IntegerField(null=True, blank=True, default=0, verbose_name = "Punzioni offensive a sinistra Primo Tempo Squadra A")
    cross_dx1A = models.IntegerField(null=True, blank=True, default=0, verbose_name = "Cross a destra Primo Tempo Squadra A")
    cross_cc1A = models.IntegerField(null=True, blank=True, default=0, verbose_name = "Cross al centro Primo Tempo Squadra A")
    cross_sx1A = models.IntegerField(null=True, blank=True, default=0, verbose_name = "Cross a sinistra Primo Tempo Squadra A")
    corners1A = models.IntegerField(null=True, blank=True, default=0, verbose_name = "Calci d'angolo Primo Tempo Squadra A")
    parate1A = models.IntegerField(null=True, blank=True, default=0, verbose_name = "Parate Primo Tempo Squadra A")
    fuorigioco1A = models.IntegerField(null=True, blank=True, default=0, verbose_name = "Fuorigioco Primo Tempo Squadra A")
    tiri_in_porta1B_sx = models.IntegerField(null=True, blank=True, default=0, verbose_name = "Tiri in porta a sinistra Primo Tempo Squadra B")
    tiri_in_porta1B_dx = models.IntegerField(null=True, blank=True, default=0, verbose_name = "Tiri in porta a destra Primo Tempo Squadra B")
    tiri_in_porta1B_cc = models.IntegerField(null=True, blank=True, default=0, verbose_name = "Tiri in porta al centro Primo Tempo Squadra B")
    tiri_in_fuori1B_sx = models.IntegerField(null=True, blank=True, default=0, verbose_name = "Tiri in fuori a sinistra Primo Tempo Squadra B")
    tiri_in_fuori1B_dx = models.IntegerField(null=True, blank=True, default=0, verbose_name = "Tiri in fuori a destra Primo Tempo Squadra B")
    tiri_in_fuori1B_cc = models.IntegerField(null=True, blank=True, default=0, verbose_name = "Tiri in fuori al centro Primo Tempo Squadra B")
    punizioni_difensive1B_sx = models.IntegerField(null=True, blank=True, default=0, verbose_name = "Punizioni difensive a sinistra Primo Tempo Squadra B")
    punizioni_difensive1B_dx = models.IntegerField(null=True, blank=True, default=0, verbose_name = "Punizioni difensive a destra Primo Tempo Squadra B")
    punizioni_difensive1B_cc = models.IntegerField(null=True, blank=True, default=0, verbose_name = "Punizioni difensive al centro Primo Tempo Squadra B")
    punizioni_offensive1B_sx = models.IntegerField(null=True, blank=True, default=0, verbose_name = "Punzioni offensive a sinistra Primo Tempo Squadra B")
    punizioni_offensive1B_dx = models.IntegerField(null=True, blank=True, default=0, verbose_name = "Punzioni offensive a destra Primo Tempo Squadra B")
    punizioni_offensive1B_cc = models.IntegerField(null=True, blank=True, default=0, verbose_name = "Punzioni offensive al centro Primo Tempo Squadra B")
    punizioni_offensive1B_sx = models.IntegerField(null=True, blank=True, default=0, verbose_name = "Punzioni offensive a sinistra Primo Tempo Squadra B")
    cross_dx1B = models.IntegerField(null=True, blank=True, default=0, verbose_name = "Cross a destra Primo Tempo Squadra B")
    cross_cc1B = models.IntegerField(null=True, blank=True, default=0, verbose_name = "Cross al centro Primo Tempo Squadra B")
    cross_sx1B = models.IntegerField(null=True, blank=True, default=0, verbose_name = "Cross a sinistra Primo Tempo Squadra B")
    corners1B = models.IntegerField(null=True, blank=True, default=0, verbose_name = "Calci d'angolo Primo Tempo Squadra B")
    parate1B = models.IntegerField(null=True, blank=True, default=0, verbose_name = "Parate Primo Tempo Squadra B")
    fuorigioco1B = models.IntegerField(null=True, blank=True, default=0, verbose_name = "Fuorigioco Primo Tempo Squadra B")
    tiri_in_porta2A_sx = models.IntegerField(null=True, blank=True, default=0, verbose_name = "Tiri in porta a sinistra Secondo Tempo Squadra A")
    tiri_in_porta2A_dx = models.IntegerField(null=True, blank=True, default=0, verbose_name = "Tiri in porta a destra Secondo Tempo Squadra A")
    tiri_in_porta2A_cc = models.IntegerField(null=True, blank=True, default=0, verbose_name = "Tiri in porta al centro SecondoTempo Squadra A")
    tiri_in_fuori2A_sx = models.IntegerField(null=True, blank=True, default=0, verbose_name = "Tiri in fuori a sinistra Secondo Tempo Squadra A")
    tiri_in_fuori2A_dx = models.IntegerField(null=True, blank=True, default=0, verbose_name = "Tiri in fuori a destra Secondo Tempo Squadra A")
    tiri_in_fuori2A_cc = models.IntegerField(null=True, blank=True, default=0, verbose_name = "Tiri in fuori al centro SecondoTempo Squadra A")
    punizioni_difensive2A_sx = models.IntegerField(null=True, blank=True, default=0, verbose_name = "Punizioni difensive a sinistra Secondo Tempo Squadra A")
    punizioni_difensive2A_dx = models.IntegerField(null=True, blank=True, default=0, verbose_name = "Punizioni difensive a destra Secondo Tempo Squadra A")
    punizioni_difensive2A_cc = models.IntegerField(null=True, blank=True, default=0, verbose_name = "Punizioni difensive al centro SecondoTempo Squadra A")
    punizioni_offensive2A_sx = models.IntegerField(null=True, blank=True, default=0, verbose_name = "Punzioni offensive a sinistra Secondo Tempo Squadra A")
    punizioni_offensive2A_dx = models.IntegerField(null=True, blank=True, default=0, verbose_name = "Punzioni offensive a destra Secondo Tempo Squadra A")
    punizioni_offensive2A_cc = models.IntegerField(null=True, blank=True, default=0, verbose_name = "Punzioni offensive al centro SecondoTempo Squadra A")
    punizioni_offensive2A_sx = models.IntegerField(null=True, blank=True, default=0, verbose_name = "Punzioni offensive a sinistra Secondo Tempo Squadra A")
    cross_dx2A = models.IntegerField(null=True, blank=True, default=0, verbose_name = "Cross a destra Secondo Tempo Squadra A")
    cross_cc2A = models.IntegerField(null=True, blank=True, default=0, verbose_name = "Cross al centro SecondoTempo Squadra A")
    cross_sx2A = models.IntegerField(null=True, blank=True, default=0, verbose_name = "Cross a sinistra Secondo Tempo Squadra A")
    corners2A = models.IntegerField(null=True, blank=True, default=0, verbose_name = "Calci d'angolo Secondo Tempo Squadra A")
    parate2A = models.IntegerField(null=True, blank=True, default=0, verbose_name = "Parate Secondo Tempo Squadra A")
    fuorigioco2A = models.IntegerField(null=True, blank=True, default=0, verbose_name = "Fuorigioco Secondo Tempo Squadra A")
    tiri_in_porta2B_sx = models.IntegerField(null=True, blank=True, default=0, verbose_name = "Tiri in porta a sinistra Secondo Tempo Squadra B")
    tiri_in_porta2B_dx = models.IntegerField(null=True, blank=True, default=0, verbose_name = "Tiri in porta a destra Secondo Tempo Squadra B")
    tiri_in_porta2B_cc = models.IntegerField(null=True, blank=True, default=0, verbose_name = "Tiri in porta al centro SecondoTempo Squadra B")
    tiri_in_fuori2B_sx = models.IntegerField(null=True, blank=True, default=0, verbose_name = "Tiri in fuori a sinistra Secondo Tempo Squadra B")
    tiri_in_fuori2B_dx = models.IntegerField(null=True, blank=True, default=0, verbose_name = "Tiri in fuori a destra Secondo Tempo Squadra B")
    tiri_in_fuori2B_cc = models.IntegerField(null=True, blank=True, default=0, verbose_name = "Tiri in fuori al centro SecondoTempo Squadra B")
    punizioni_difensive2B_sx = models.IntegerField(null=True, blank=True, default=0, verbose_name = "Punizioni difensive a sinistra Secondo Tempo Squadra B")
    punizioni_difensive2B_dx = models.IntegerField(null=True, blank=True, default=0, verbose_name = "Punizioni difensive a destra Secondo Tempo Squadra B")
    punizioni_difensive2B_cc = models.IntegerField(null=True, blank=True, default=0, verbose_name = "Punizioni difensive al centro SecondoTempo Squadra B")
    punizioni_offensive2B_sx = models.IntegerField(null=True, blank=True, default=0, verbose_name = "Punzioni offensive a sinistra Secondo Tempo Squadra B")
    punizioni_offensive2B_dx = models.IntegerField(null=True, blank=True, default=0, verbose_name = "Punzioni offensive a destra Secondo Tempo Squadra B")
    punizioni_offensive2B_cc = models.IntegerField(null=True, blank=True, default=0, verbose_name = "Punzioni offensive al centro SecondoTempo Squadra B")
    punizioni_offensive2B_sx = models.IntegerField(null=True, blank=True, default=0, verbose_name = "Punzioni offensive a sinistra Secondo Tempo Squadra B")
    cross_dx2B = models.IntegerField(null=True, blank=True, default=0, verbose_name = "Cross a destra Secondo Tempo Squadra B")
    cross_cc2B = models.IntegerField(null=True, blank=True, default=0, verbose_name = "Cross al centro SecondoTempo Squadra B")
    cross_sx2B = models.IntegerField(null=True, blank=True, default=0, verbose_name = "Cross a sinistra Secondo Tempo Squadra B")
    corners2B = models.IntegerField(null=True, blank=True, default=0, verbose_name = "Calci d'angolo Secondo Tempo Squadra B")
    parate2B = models.IntegerField(null=True, blank=True, default=0, verbose_name = "Parate Secondo Tempo Squadra B")
    fuorigioco2B = models.IntegerField(null=True, blank=True, default=0, verbose_name = "Fuorigioco Secondo Tempo Squadra B")
    
    def __str__(self):
        return ("Statistiche della partita " + str(self.match.team_a) + " vs " + str(self.match.team_b) + " del " + str(self.match.date))
    class Meta:
            verbose_name_plural = "Statistiche"

